### ISSUE TITLE
Every refresh will send the page to Login

### ISSUE THREAD

**Issue by xinwkc** [TwanoO67/bootstraping-ngx-admin-lte#101]
Hi, Can you please help for this issue,

Every time, when I press refresh page from Browser, it will be directed to Login page. Is there a way to avoid this?

Thanks,

**Comment by TwanoO67** [comment]
Hello,

On a page refresh, the can-activate-guard will be called:
https://github.com/TwanoO67/ngx-admin-lte/blob/develop/src/services/can-activate-guard.service.ts

At the moment your user is not connected, so it will send you to the login route.

If you want your user to acces a page using the AuthLayout, it should have the state "connected",
and so you have to provide a way to test that state.
(or force it to be always connected)

**Comment by xinwkc** [comment]
Thank you for the quick turn around, I'll try this

**Comment by xinwkc** [comment]
Issue closed, thanks!
