### ISSUE TITLE
When I click button home it turn to / but not 'home'

### ISSUE THREAD

**Issue by elevensheep** [TwanoO67/bootstraping-ngx-admin-lte#78]
When I click button home it turn to / but not 'home'
![6833787f-f589-4151-bf79-65bdcb9e8be9](https://cloud.githubusercontent.com/assets/5299426/23996695/544e806a-0a89-11e7-8897-4e7557f75190.png)

**Comment by giatuyentiensinh** [comment]
You should change file `app.component.ts` link of title home to `/home`

**Comment by TwanoO67** [comment]
There is maybe a route missing. 
I will look at that.

Thanks for the report :)
