### ISSUE TITLE
Angular 4 and Angular-CLI last version

### ISSUE THREAD

**Issue by jaceee** [TwanoO67/bootstraping-ngx-admin-lte#80]
I can make a pull request if you point me in the right direction

**Comment by TwanoO67** [comment]
Hello.

It should be easy to have à working version.
Just créate à new angular4 project and move ts file.
The long part would be to lint the project with thé new rules.

**Comment by TwanoO67** [comment]
FYI, I'm doing a full refactor to answer your request.
It would be 2 different repo, one with an npm package (containing services, layouts and widgets)
oand the current repo will be using the npm package as a dependancy.

This way it would be easier for everyone to manage update of the package
( and it would respond to https://github.com/TwanoO67/ng2-admin-lte/issues/34 )

But it's a lot of work to rewrite all the things and separate both repo, (and I haven't many time for that at the moment) so first version of this would probably take a month

**Comment by jaceee** [comment]
Glad to know, I am already finishing my work with this dashboard and I
totally love it. If you create a branch for the changes and create tag
issues for the pending work I would be happy to contribute.

Keep up the good work.

**Comment by TwanoO67** [comment]
First version is done, i'm counting on you to help make it better ;)
