### ISSUE TITLE
Its not working for me in IE10

### ISSUE THREAD

**Issue by cravikumar** [TwanoO67/bootstraping-ngx-admin-lte#81]
I jus downloaded the whole zip and executed below,
npm-install
npm-start

Below is the error that i see in console

![console error](https://cloud.githubusercontent.com/assets/28348421/25659634/4dbaaba8-3026-11e7-88eb-cf1ae3ef7c39.PNG)

**Comment by nileshyadav326** [comment]
i am also getting the same error have u found any solution on the same.

**Comment by TwanoO67** [comment]
Install with yarn to ensure correct dependancies version

**Comment by nileshyadav326** [comment]
nope same issue.
done the new checkout of this repo and install all dependency with yarn same issue.

![image](https://user-images.githubusercontent.com/3830025/28035247-9d1c3c26-65d1-11e7-949d-8482d971b0a9.png)

**Comment by TwanoO67** [comment]
This repo asn't change the last 5 month ( except for @nileshyadav326 merge ).
And I still using it on ubuntu and it's working.
So: 
Maybe something in windows as changed... (but i don't think so...)
Or something change in the dependancies.

But I have no window computer to test on it sorry :/

**Comment by TwanoO67** [comment]
Hello guys,

I made a new version with angular4.
can you confirm if the bug is fixed now ?

**Comment by nileshyadav326** [comment]
once we uncomment the below lines from polyfill.js its working fine

/** IE9, IE10 and IE11 requires all of the following polyfills. **/
 import 'core-js/es6/symbol';
 import 'core-js/es6/object';
 import 'core-js/es6/function';
 import 'core-js/es6/parse-int';
 import 'core-js/es6/parse-float';
 import 'core-js/es6/number';
 import 'core-js/es6/math';
 import 'core-js/es6/string';
 import 'core-js/es6/date';
 import 'core-js/es6/array';
 import 'core-js/es6/regexp';
 import 'core-js/es6/map';
 import 'core-js/es6/set';

**Comment by TwanoO67** [comment]
Can you confirm it's fixed ?

**Comment by nileshyadav326** [comment]
yes, it's working fine tested in IE 11 and above.

**Comment by TwanoO67** [comment]
Thank you ;)
