### ISSUE TITLE
Problem with ng build --prod

### ISSUE THREAD

**Issue by iserifith** [TwanoO67/bootstraping-ngx-admin-lte#87]
`ERROR in /home/user/workspace/adminlte/src/$$_gendir/node_modules/ngx-admin-lte/src/layouts/auth/auth.ngfactory.ts (93,31): Property 'mylinks' is private and only accessible within class 'LayoutAuthComponent'.

ERROR in ng:///home/user/workspace/adminlte/node_modules/ngx-admin-lte/src/layouts/auth/auth.html (6,3): Property 'toastrConfig' is private and only accessible within class 'LayoutAuthComponent'.

ERROR in ng:///home/user/workspace/adminlte/node_modules/ngx-admin-lte/src/widgets/logo/logo.component.html (3,1): Property 'logo' is private and only accessible within class 'LogoComponent'.

ERROR in ng:///home/user/workspace/adminlte/node_modules/ngx-admin-lte/src/widgets/logo/logo.component.html (4,29): Property 'logo' is private and only accessible within class 'LogoComponent'.

ERROR in ng:///home/user/workspace/adminlte/node_modules/ngx-admin-lte/src/widgets/logo/logo.component.html (4,52): Property 'logo' is private and only accessible within class 'LogoComponent'.

ERROR in ng:///home/user/workspace/adminlte/node_modules/ngx-admin-lte/src/widgets/logo/logo.component.html (5,27): Property 'logo' is private and only accessible within class 'LogoComponent'.

ERROR in /home/user/workspace/adminlte/src/$$_gendir/node_modules/ngx-admin-lte/src/widgets/menu-aside/menu-aside.component.ngfactory.ts (327,36): Property 'links' is private and only accessible within class 'MenuAsideComponent'.

ERROR in /home/user/workspace/adminlte/src/$$_gendir/node_modules/ngx-admin-lte/src/widgets/menu-aside/menu-aside.component.ngfactory.ts (331,37): Property 'currentUser' is private and only accessible within class 'MenuAsideComponent'.

ERROR in /home/user/workspace/adminlte/src/$$_gendir/node_modules/ngx-admin-lte/src/widgets/menu-aside/menu-aside.component.ngfactory.ts (331,78): Property 'currentUser' is private and only accessible within class 'MenuAsideComponent'.

ERROR in ng:///home/user/workspace/adminlte/node_modules/ngx-admin-lte/src/widgets/menu-aside/menu-aside.component.html (9,10): Property 'currentUser' is private and only accessible within class 'MenuAsideComponent'.

ERROR in ng:///home/user/workspace/adminlte/node_modules/ngx-admin-lte/src/widgets/menu-aside/menu-aside.component.html (9,10): Property 'currentUser' is private and only accessible within class 'MenuAsideComponent'.

ERROR in ng:///home/user/workspace/adminlte/node_modules/ngx-admin-lte/src/widgets/menu-aside/menu-aside.component.html (10,6): Property 'currentUser' is private and only accessible within class 'MenuAsideComponent'.

ERROR in ng:///home/user/workspace/adminlte/node_modules/ngx-admin-lte/src/widgets/menu-aside/menu-aside.component.html (9,5): Property 'currentUser' is private and only accessible within class 'MenuAsideComponent'.

ERROR in /home/user/workspace/adminlte/src/$$_gendir/node_modules/ngx-admin-lte/src/widgets/messages-box/messages-box.component.ngfactory.ts (94,31): Property 'messages' is private and only accessible within class 'MessagesBoxComponent'.

ERROR in /home/user/workspace/adminlte/src/$$_gendir/node_modules/ngx-admin-lte/src/widgets/messages-box/messages-box.component.ngfactory.ts (98,31): Property 'messages' is private and only accessible within class 'MessagesBoxComponent'.

ERROR in ng:///home/user/workspace/adminlte/node_modules/ngx-admin-lte/src/widgets/messages-box/messages-box.component.html (8,21): Property 'msgLength' is private and only accessible within class 'MessagesBoxComponent'.

ERROR in ng:///home/user/workspace/adminlte/node_modules/ngx-admin-lte/src/widgets/notification-box/notification-box.component.html (7,21): Property 'notifLength' is private and only accessible within class 'NotificationBoxComponent'.

ERROR in ng:///home/user/workspace/adminlte/node_modules/ngx-admin-lte/src/widgets/tasks-box/tasks-box.component.html (7,21): Property 'tasksLength' is private and only accessible within class 'TasksBoxComponent'.

ERROR in ng:///home/user/workspace/adminlte/node_modules/ngx-admin-lte/src/widgets/user-box/user-box.component.html (36,10): Property 'logout' is private and only accessible within class 'UserBoxComponent'.

ERROR in /home/user/workspace/adminlte/src/$$_gendir/node_modules/ngx-admin-lte/src/widgets/user-box/user-box.component.ngfactory.ts (90,35): Property 'currentUser' is private and only accessible within class 'UserBoxComponent'.

ERROR in ng:///home/user/workspace/adminlte/node_modules/ngx-admin-lte/src/widgets/user-box/user-box.component.html (5,8): Property 'currentUser' is private and only accessible within class 'UserBoxComponent'.

ERROR in ng:///home/user/workspace/adminlte/node_modules/ngx-admin-lte/src/widgets/user-box/user-box.component.html (5,57): Property 'currentUser' is private and only accessible within class 'UserBoxComponent'.

ERROR in ng:///home/user/workspace/adminlte/node_modules/ngx-admin-lte/src/widgets/user-box/user-box.component.html (7,27): Property 'currentUser' is private and only accessible within class 'UserBoxComponent'.

ERROR in ng:///home/user/workspace/adminlte/node_modules/ngx-admin-lte/src/widgets/user-box/user-box.component.html (12,10): Property 'currentUser' is private and only accessible within class 'UserBoxComponent'.

ERROR in ng:///home/user/workspace/adminlte/node_modules/ngx-admin-lte/src/widgets/user-box/user-box.component.html (12,59): Property 'currentUser' is private and only accessible within class 'UserBoxComponent'.

ERROR in ng:///home/user/workspace/adminlte/node_modules/ngx-admin-lte/src/widgets/user-box/user-box.component.html (13,8): Property 'currentUser' is private and only accessible within class 'UserBoxComponent'.

ERROR in ng:///home/user/workspace/adminlte/node_modules/ngx-admin-lte/src/widgets/user-box/user-box.component.html (13,8): Property 'creation_date' does not exist on type 'User'.

ERROR in /home/user/workspace/adminlte/src/$$_gendir/node_modules/ngx-admin-lte/src/widgets/breadcrumb/breadcrumb.component.ngfactory.ts (96,31): Property 'display' is private and only accessible within class 'BreadcrumbComponent'.

ERROR in /home/user/workspace/adminlte/src/$$_gendir/app/pages/page-num/page-num.component.ngfactory.ts (23,35): Property 'id' is private and only accessible within class 'PageNumComponent'.

ERROR in ng:///home/user/workspace/adminlte/src/app/pages/login/login.component.html (7,100): Property 'email' is private and only accessible within class 'LoginComponent'.

ERROR in ng:///home/user/workspace/adminlte/src/app/pages/login/login.component.html (20,109): Property 'password' is private and only accessible within class 'LoginComponent'.

ERROR in ng:///home/user/workspace/adminlte/src/app/pages/login/login.component.html (43,72): Property 'login' is private and only accessible within class 'LoginComponent'.

ERROR in ng:///home/user/workspace/adminlte/src/app/pages/login/login.component.html (7,89): Property 'email' is private and only accessible within class 'LoginComponent'.

ERROR in ng:///home/user/workspace/adminlte/src/app/pages/login/login.component.html (20,95): Property 'password' is private and only accessible within class 'LoginComponent'.

ERROR in ./src/main.ts
Module not found: Error: Can't resolve './$$_gendir/app/app.module.ngfactory' in '/home/user/workspace/adminlte/src'
 @ ./src/main.ts 4:0-74
 @ multi ./src/main.ts
`

It works fine with only ng build tho

**Comment by TwanoO67** [comment]
This should be fixed by the new version.
Can you confirm ?
