### ISSUE TITLE
Can class "content" remove inner box style

### ISSUE THREAD

**Issue by kentkwan** [TwanoO67/bootstraping-ngx-admin-lte#88]
Most of time we need to custom our box style or add many of boxes in content.
But there is a box style in auth.html like this.

```html
<!-- Main content -->
<section class="content">
  <div class="box box-default">
    <div class="box-body">
      <router-outlet></router-outlet>
    </div>
  </div>
</section>
<!-- /.content -->
```

**Comment by TwanoO67** [comment]
Hello.
What are suggesting ?
Adding a new layout in ngx-admin-lte for that ?
or maybe adding a new widgets for handling boxing style ?

**Comment by kentkwan** [comment]
I will suggest that adding box widget

**Comment by TwanoO67** [comment]
You can now set the boxed_style option to false in your route layouts
