### ISSUE TITLE
docker image and linux problem with ng serve

### ISSUE THREAD

**Issue by xMase** [TwanoO67/bootstraping-ngx-admin-lte#89]
In the current release there is a problem with linux ng serve.
Docker Ng serve by default listen on 127.0.0.1 but the  socket is no bound directly to the host machine socket, with the problem that 127.0.0.1:4900 does not answer. To resolve the problem ng serve must be forced to use `all interface` 0.0.0.0.

in package.json change:
7     "start": "ng serve",
to:
7    "start": "ng serve --host 0.0.0.0",

**Comment by TwanoO67** [comment]
Thanks for the comment, it's done in develop and will be in the next version
