### ISSUE TITLE
How to deploy the application on production 

### ISSUE THREAD

**Issue by nileshyadav326** [TwanoO67/bootstraping-ngx-admin-lte#90]
Hi ,

Kindly help to deploy the application on production.

when I run the application on production using terminal it (npm start command is working fine but when I close the terminal it stops )

Any suggestion?

**Comment by TwanoO67** [comment]
In production tou should not use the node server. 
You should build your app with "ng build --prod" then serve the dist result via apache or nginx

**Comment by TwanoO67** [comment]
Any update on that ?

**Comment by nileshyadav326** [comment]
it's working fine using Tomcat to serve the application. previously installed node js and all dependencies 
but after your suggestion using **ng build --env=prod** command to generate the files.

Thanks.
