### ISSUE TITLE
package.json script gen

### ISSUE THREAD

**Issue by xMase** [TwanoO67/bootstraping-ngx-admin-lte#94]
On current master release branch gen script is missing or the current guidelines must be up-to-date

`"scripts": {
    "ng": "ng",
    "start": "ng serve --host 0.0.0.0",
    "build": "ng build",
    "prod": "ng build --prod",
    "test": "ng test",
    "lint": "ng lint",
    "e2e": "ng e2e"
  },`

**Comment by TwanoO67** [comment]
Hello,

Thanks for the issue, you should now use "yarn ng g"
It has been updated in the readme :)
