### ISSUE TITLE
I want to be a contributor

### ISSUE THREAD

**Issue by AndresJz** [TwanoO67/bootstraping-ngx-admin-lte#95]
Hi, 
I am fascinated with your work, and I would like to add some features to you current project Also I am working on a beautiful project but I need to make some modifications to the interface.
I am Wondering if I could make a public version on NPM Packages, 
I look forward to hearing from you.

**Comment by TwanoO67** [comment]
Hello @AndresJz,

The project is open to new feature and help is always appreciated :)

Concerning the npm package, there's already one named "ngx-admin-lte" which packages all the reusable part of this project.
But maybe I didnt understood what you need ?

**Comment by AndresJz** [comment]
I would like to create a Branch where I made especific changes, like allow to change the footer, disable some buttons, even in the logo allow to insert an image instead of Only Text, I have more ideas, In the future if It is possible I consider to publsh another version when other people can be download option 2. But Also Is possible to keep the packages in the same repository I think.

Regards

**Comment by TwanoO67** [comment]
Hello,
As long as the modification are customizable you can post on the original repo and i will merge it :)

**Comment by TwanoO67** [comment]
Hello,

Following your suggestion I made modification to allow changing the footer.
