### ISSUE TITLE
There is no menu in aside menu list

### ISSUE THREAD

**Issue by yzhang921** [TwanoO67/bootstraping-ngx-admin-lte#96]
Hi, I'm a rookie for angular4. don't know if this is a bug or not. 
Looks like ngOnInit method in AppComponent doesn't run. 

![image](https://user-images.githubusercontent.com/6037522/33057653-f39fa70a-cec6-11e7-8f8b-b306fa80b4c7.png)

**Comment by TwanoO67** [comment]
Hello,

Thanks for the report.
The project need a new version of ngx-admin-lte to correct that.
In the meantime you should use master branch not develop

**Comment by yzhang921** [comment]
It works now, thanks for your quick reply!
